name: flutter_screenutil_plus
description: A flutter plugin for adapting screen and font size. Guaranteed to look good on different models
version: 1.1.1
homepage: https://github.com/muhammadkamel/flutter_screenutil_plus
repository: https://github.com/muhammadkamel/flutter_screenutil_plus
license: MIT

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
